version: "3.3"
services:
  template-database: 
    ports:
      - "1433:1433"
  template-api:
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8273:80"
    depends_on: 
      - template-database
  client-ui:  
    ports:
      - "51000:3000"
    depends_on: 
      - template-api
      - message-queue
  add-value-handler:
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - message-queue
networks:
  template-net:
    external:
      name: nat
    

   