version: "3.3"
services:
  template-database: 
    ports:
      - "1433:1433"
  template-api:
    depends_on: 
      - template-database
  client-ui:  
    ports:
      - "51000:3000"
    depends_on: 
      - template-api
      - message-queue
  message-queue:
    

   